### PR TITLE
Implement Headers

### PR DESCRIPTION
**Pull request by BladeFireLight**
Headers were not initialized and Dictionary did not convert to WebHeaderCollection. so I changed the type. 
Addresses issue #84

### CODE REVIEW

**Comment by BladeFireLight** [comment]
Travis failed on pester?

**Comment by tylerl0706** [comment]
Ah. I believe the PowerShell team removed Pester as a dependency recently. We'll need to update the Travis build to install Pester.

**Comment by BladeFireLight** [comment]
Do I need to do anything to trigger the Travis tests?

**Comment by tylerl0706** [comment]
@BladeFireLight Just merged in the fix for this: https://github.com/PowerShell/Polaris/pull/86

just grab the latest master bits via merge or rebase and you should be good to go

**Comment by tylerl0706** [comment]
Also, I'd really like to see at least one Pester test for this so that we can avoid this in the future. I think it would be an addition here:

Add a route that sends back a test header here:
https://github.com/PowerShell/Polaris/blob/master/test/PolarisServer.ps1

And then do an Invoke-WebRequest and check to make sure the header is in the response here:
https://github.com/PowerShell/Polaris/blob/master/test/PolarisServer.Tests.ps1

**Comment by BladeFireLight** [comment]
I noticed while setting this up all the tests are dependent on IE. and IE having been run once under the profile that runs the test.  Unless the tests actually required IE's rendering engine, why not use -UseBasicParsing?

**Comment by tylerl0706** [comment]
You're right. We should be using `-UseBasicParsing`

**Comment by tylerl0706** [comment]
This PR looks great! Thanks for contributing!

**Pull request merged**
