### PR TITLE
Fixes #190: New authentication documentation

### LINKED ISSUE #190: Question: Authentication
Hi @Tiberriver256 / @TylerLeonhardt 

I was scanning your documentation summary for information on 'Authentication'. Unfortunatley, I couldn't find a topic called like that (Perhaps it is simply hidden somwhere else?).

I was trying to figure out if it was possible to handle some authentication stuff (like, this member of this AD group, cannot access to this route).

I think I read something in that direction once, and couldn't find it. Would you mind pointing me in the right direction?

Thanks

#Stéphane

### PR DESCRIPTION
**Pull request by Tiberriver256**
This PR contains two things:

1. I added in the documentation for authentication
2. @Badgerati reminded me in #190 that it was impossible to implement custom authentication methods from Polaris middlewares because we were unable to send a response from a middleware. I made a small change to allow responses to be sent from middleware which now allows us to write authentication middleware! Check out the sample in the docs.

### Pull Request Creation Checklist

-   [x] Useful title (i.e. **Fix #XXX: Description** / **Feature #XXX: Description** / **RFC #XXX: Description**)
-   [x] Description of the changes you are making
-   [x] Added a link to the related Github issue in the description (i.e. type `Fixes #XXX` in the desciption of the PR)
-   [x] If you are still working on the code and would like some early feedback via the Pull Request process just add [WIP] to the beginning of your Pull Request title
-   [x] Checked the [Polaris GitHub workflow guidance](/GITHUB_GUIDANCE.md) to make sure my code has the latest changes made to the master branch
-   [x] Throw small party 🎉

Fixes #190

### CODE REVIEW

**Comment by Tiberriver256** [comment]
Tests did not run unless I missed something :(

**Comment by TylerLeonhardt** [comment]
Hmm that's odd

**Comment by Tiberriver256** [comment]
Could you manually kick it off?

**Comment by TylerLeonhardt** [comment]
I can’t for the life of me fix this… may need to move it to Azure Pipelines

**Comment by Tiberriver256** [comment]
Oooo that would be awesome

**Comment by TylerLeonhardt** [comment]
ok! Moved over. Can you rebase? That should fire CI

**Comment by Tiberriver256** [comment]
Success! Thanks!

**Comment by TylerLeonhardt** [comment]
Hmm I'm seeing the CI yamls in your changes which is odd... Can you maybe reopen this or something?

**Comment by Tiberriver256** [comment]
Squashed and it looks like Github is happy with me now.

**Pull request merged**
