### PR TITLE
[WIP] Add Polaris container example

### PR DESCRIPTION
**Pull request by Stijnc**
See #144 for more information.

It adds a how-to guide to deploy a pshtml generated website running on a polaris webserver in a linux container.
Additionally we deploy the container on kubernetes (AKS) and expose the service to an Azure loadbalancer.

as there is no dedicated branch, I created the pull request targeting the master branch.

Is the format ok?

will squash commits once work is complete.

*Edit from maintainer:
Related issue #135

### CODE REVIEW

**Comment by tylerl0706** [comment]
This is looking good! I'll have a deeper look later but here's my initial comments on layout.

I would like the `example` folder to be a flat list of examples (or maybe it should be called `examples`). So can you please give the `container` folder a name that explains the example a bit more and then put everything you need inside of that?

Also, nitpick, it's usually best practice to include new lines at the end of files.😊

**Comment by Stijnc** [comment]
hi @tylerl0706,

Just so I understand it correctly, I take the following folder structure in mind:
- example(s)
     | --  pshtml website running on polaris in a linux container on aks
                  | -- website
                           | -- assets
                           | -- ....
                  | -- kubernetes deployment
                  | -- dockerfile
                  | -- readme.md
if ok, will rework and modify some additional files + complete the readme to have a step by step instruction from website to container to aks.

**Comment by tylerl0706** [comment]
GitHub didn't render that correctly but I edited the message and saw what you meant and it looks good!

I'd recommend not using spaces in the path though. Maybe:

`examples/kubernetes-linux-container-pshtml`

**Comment by tylerl0706** [comment]
If you have any other questions let me know, otherwise once you address that structure I'm happy to merge this in. Once that happens, I'm showing this to my team - they're gonna love it!

**Comment by Stijnc** [comment]
I have a couple of time constraints, but hopefully I get this ready by end of week.
(I'm polishing everything a bit and writing the how-to guide).
On Thursday I have an internal demo to validate the example walk-through.

**Comment by TylerLeonhardt** [comment]
@Stijnc gentle ping - don't want this to disappear!

**Comment by Stephanevg** [comment]
Yeah, It would be great to have this example I agree

**Pull request closed without merging**
