### PR TITLE
Update Polaris.Class.ps1

### PR DESCRIPTION
**Pull request by DigitalDrifta**
Fixing issue where an invalid URL would return valid results. Discussed here: https://github.com/PowerShell/Polaris/issues/116

### CODE REVIEW

**Comment by tylerl0706** [comment]
AppVeyor where did you go? 😥

**Comment by tylerl0706** [comment]
AppVeyor is drunk I guess, here's the CI build:
https://ci.appveyor.com/project/PowerShell/polaris/build/job/0qxc0cy0p5bd54g9

Looks like there are a couple test failures with this change.

**Comment by tylerl0706** [comment]
It's probably from some bad assumptions we made when we had -match :/

**Comment by Tiberriver256** [comment]
Oofta, yeah quite the oversight on my part. Thanks for pointing that out @DigitalDrifta and thanks a lot for the PR. I think this may actually take a bit of work to make sure file serving still works. I'll see what I can work up for this tonight.

**Comment by TimCurwick** [comment]
I just finished building several Polaris-based tools and solutions that I'm presenting at MMS next week, including simple, yet powerful tools for dynamically serving somewhat static content.

This bugfix breaks most of my tools and solutions, which rely on partial route matching.

The bug does need to be fixed--I had to implement an alternate fix for my tools to work correctly--but I recommend we add an enhancement that allows for control over exact or partial matching rather than dictating one or the other.

I can submit an alternate PR after the conference.

**Comment by Tiberriver256** [comment]
Hey @TimCurwick,

Wow! If you get it on video let me know. Sounds like some awesome stuff!

I think we’re all in the same boat here with needing both strict and dynamic matching and it’s going to need quite a bit more work than this PR (although we SUPER appreciate PRs like this). I’m working on implementing path based parameters as a solution to the problem.

https://github.com/PowerShell/Polaris/pull/119

It will probably be a breaking change but migration should be as easy as adding a parameter to the part of your path you expect to be dynamic.

@tylerl0706 - Are we okay closing this PR out?

**Comment by tylerl0706** [comment]
Sounds good! Really appreciate the PR @DigitalDrifta but unfortunately, (and this is really our fault) this is not as simple to fix as I initially thought.

@Tiberriver256's awesome PR will fix up this pain point, while adding a highly requested feature :)

I'm going to close this in favor of that.

Thanks again!

**Pull request closed without merging**
