### PR TITLE
Add ClientIP to PolarisRequest.Class.ps1

### PR DESCRIPTION
**Pull request by Hvid**
We need to be able to retrieve the client IP.

### CODE REVIEW

**Comment by Tiberriver256** [comment]
Hi Hvid!

Thanks for the PR. I think that's pretty clean and we can pull it in but I've been wondering about use cases like this where there are reasons people might need / want to access data on the original raw request.

@tylerl0706 - Would making the rawrequest a non-hidden field be a better way to support things like this?

You would end up doing something closer to this if it was needed

```ps
$Request.RawRequest.RemoteEndpoint.Address
```

**Comment by Hvid** [comment]
Hi Micah,

Use cases could be logging and making decisions based on where the request originates from.

**Comment by Tiberriver256** [comment]
Definitely a worthy use case. Would having the rawrequest available work as well?

**Comment by Hvid** [comment]
Sure, as long as we can retrieve the IP :)

**Comment by tylerl0706** [comment]
I really like having a RawRequest so that folks can use the underlying HttpListenerRequest object if they need something specific that not everyone else needs.

That said, ClientIp seems like a good one to add and I think a decent lot of people would use it.

**Comment by Hvid** [comment]
In my opinion, the ClientIP should be exposed directly as a property on the $request object, as it's a value a lot of people will find useful. Having the RawRequest hidden is fine for keeping it clean, as it can still be accessed by explicitly getting $request.RawRequest, if needed.

**Comment by tylerl0706** [comment]
@Tiberriver256 I'll wait on your sign off before merging :)

**Comment by Tiberriver256** [comment]
Sounds good to me. 

Could you remove the hidden attribute from the raw request in that class too? 

Get it all on one PR.

**Comment by Hvid** [comment]
Sure, done.

**Comment by Tiberriver256** [comment]
Thanks!

**Comment by tylerl0706** [comment]
Thanks again :) https://twitter.com/TylerLeonhardt/status/984260821365608448

**Pull request merged**
